name: Create Release and Upload Asset

on:
    push:
        tags:
            - 'v*'

jobs:
    build_and_release:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Select latest stable Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.2'

            - name: Build Swift helper for Universal Binary
              run: |
                  # Intel (x86_64)向けにビルド
                  swift build -c release --arch x86_64 --package-path ./swift_helper/src

                  # Apple Silicon (arm64)向けにビルド
                  swift build -c release --arch arm64 --package-path ./swift_helper/src
                  
                  # 両方のバイナリをlipoコマンドで1つに結合
                  mkdir -p ./swift_helper/bin
                  lipo -create \
                    ./swift_helper/src/.build/x86_64-apple-macosx/release/RealmExporter \
                    ./swift_helper/src/.build/arm64-apple-macosx/release/RealmExporter \
                    -output ./swift_helper/bin/RealmExporter

            - name: Prepare assets for release
              run: |
                  mkdir clipy-history-exporter

                  cp export_clips.py clipy-history-exporter/
                  cp LICENSE clipy-history-exporter/
                  cp README.md clipy-history-exporter/

                  # 作成したユニバーサルバイナリをコピー
                  mkdir -p clipy-history-exporter/swift_helper/bin
                  cp ./swift_helper/bin/RealmExporter clipy-history-exporter/swift_helper/bin/RealmExporter

                  zip -r clipy-history-exporter-${{ github.ref_name }}.zip clipy-history-exporter

            - name: Create Release using GitHub CLI
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release create ${{ github.ref_name }} \
                --title "Release ${{ github.ref_name }}" \
                --notes "See the README for details." \
                clipy-history-exporter-${{ github.ref_name }}.zip
